FLAGPERF_PATH: "/data/home/zhengzy/FlagPerf/base"
FLAGPERF_LOG_PATH: "result"
FLAGPERF_LOG_LEVEL: "info"
# "BENCHMARK" means benchmarks(torch), "TOOLKIT" means toolkits
# benchmarks using container_main to launch "torchrun benchmarks/<case>/main.py", nnodes * nproc
# toolkits using container_main to launch bash toolkits/<case>/<vendor>/main.sh, nnodes.
# only in benchmarks, flagperf will automatically execute benchmakrs/<case>/<vendor>/requirements.txt and env.sh
# all resources to be used in toolkits/<case>/<vendor>/main.sh, should be under toolkits/<case>/<vendor>/
BENCHMARKS_OR_TOOLKITS: "BENCHMARK"
PIP_SOURCE: "https://mirror.baidu.com/pypi/simple"
# for nvidia, using "CUDA_VISIBLE_DEVICES"
# for xxx, using
NPROC_PER_NODE: 4
ACCE_VISIBLE_DEVICE_ENV_NAME: "CUDA_VISIBLE_DEVICES"
VENDOR: "nvidia"
CASES: 

     "computation-INT8:L20": "pytorch_2.3"
     "computation-FP16:L20": "pytorch_2.3"
     "computation-FP32:L20": "pytorch_2.3"
     "computation-TF32:L20": "pytorch_2.3"
     "computation-FP64:L20": "pytorch_2.3"
     "interconnect-h2d:L20": "pytorch_2.3"
     "interconnect-MPI_intraserver:L20": "pytorch_2.3"
     "interconnect-P2P_intraserver:L20": "pytorch_2.3"
     "main_memory-bandwidth:L20": "pytorch_2.3"
     "main_memory-capacity:L20": "pytorch_2.3"

# NVIDIA H100
     # "computation-INT8:H100": "pytorch_2.3"
     # "computation-FP8:H100": "pytorch_2.3"
     # "computation-FP16:H100": "pytorch_2.3"
     # "computation-FP32:H100": "pytorch_2.3"
     # "computation-TF32:H100": "pytorch_2.3"
     # "computation-FP64:H100": "pytorch_2.3"
     # "interconnect-h2d:H100": "pytorch_2.3"
     # "interconnect-MPI_intraserver:H100": "pytorch_2.3"
     # "interconnect-P2P_intraserver:H100": "pytorch_2.3"
     # "main_memory-bandwidth:H100": "pytorch_2.3"
     # "main_memory-capacity:H100": "pytorch_2.3"

# Metax C500
     # "computation-INT8:C500": "pytorch_2.3"
     # "computation-FP16:C500": "pytorch_2.3"
     # "computation-FP32:C500": "pytorch_2.3"
     # "computation-TF32:C500": "pytorch_2.3"
     # "computation-FP64:C500": "pytorch_2.3"
     # "interconnect-h2d:C500": "pytorch_2.3"
     # "interconnect-MPI_intraserver:C500": "pytorch_2.3"
     # "interconnect-P2P_intraserver:C500": "pytorch_2.3"
     # "main_memory-bandwidth:C500": "pytorch_2.3"
     # "main_memory-capacity:C500": "pytorch_2.3"


# iluvatar "computation-BF16:BI150": "pytorch_2.1"
# iluvatar "computation-FP16:BI150": "pytorch_2.1"
# iluvatar "computation-FP32:BI150": "pytorch_2.1" 
# iluvatar "main_memory-bandwidth:BI150": "pytorch_2.1"
# iluvatar "main_memory-capacity:BI150": "pytorch_2.1"
# iluvatar "interconnect-h2d:BI150": "pytorch_2.1"
# iluvatar "interconnect-MPI_intraserver:BI150": "pytorch_2.1"
# iluvatar "interconnect-MPI_interserver:BI150": "pytorch_2.1"

# nvidia "computation-FP64": "pytorch_2.3"
# nvidia "computation-FP32": "pytorch_2.3"
# nvidia "computation-TF32": "pytorch_2.3"
# nvidia "computation-FP16": "pytorch_2.3"
# nvidia "computation-BF16": "pytorch_2.3"
# nvidia "computation-INT8": "pytorch_2.3"
# nvidia "main_memory-bandwidth": "pytorch_2.3"
# nvidia "main_memory-capacity": "pytorch_2.3"
# nvidia "interconnect-h2d": "pytorch_2.3"
# nvidia "interconnect-P2P_intraserver": "pyorch_2.3"
# nvidia "interconnect-MPI_intraserver": "pytorch_2.3"
# nvidia "interconnect-P2P_interserver": "pytorch_ssh"
# nvidia "interconnect-MPI_interserver": "pytorch_ssh"

# Fine-grained chip model configuration
# nvidia "computation-FP64:A100": "pytorch_2.3"
# nvidia "computation-FP32:A100": "pytorch_2.3"
# nvidia "computation-TF32:A100": "pytorch_2.3"
# nvidia "computation-FP16:A100": "pytorch_2.3"
# nvidia "computation-BF16:A100": "pytorch_2.3"
# nvidia "computation-INT8:A100": "pytorch_2.3"
# nvidia "main_memory-bandwidth:A100": "pytorch_2.3"
# nvidia "main_memory-capacity:A100": "pytorch_2.3"
# nvidia "interconnect-h2d:A100": "pytorch_2.3"
# nvidia "interconnect-MPI_intraserver:A100": "pytorch_2.3"
# nvidia "interconnect-P2P_intraserver:A100": "pyorch_2.3"
# nvidia "interconnect-P2P_interserver:A100": "pytorch_ssh"
# nvidia "interconnect-MPI_interserver:A100": "pytorch_ssh"

# metax   "computation-FP16:C550": "pytorch_2.0"
# metax   "interconnect-h2d:C550": "pytorch_2.0"
# metax   "interconnect-MPI_interserver:C550": "pytorch_2.0"
# metax   "interconnect-MPI_intraserver:C550": "pytorch_2.0"
# metax   "interconnect-P2P_interserver:C550": "pytorch_2.0"
# metax   "interconnect-P2P_intraserver:C550": "pytorch_2.0"
# metax   "computation-FP32:C550": "pytorch_2.0"
# metax   "computation-TF32:C550": "pytorch_2.0"
# metax   "computation-BF16:C550": "pytorch_2.0"
# metax   "computation-INT8:C550": "pytorch_2.0"
# metax   "main_memory-bandwidth:C550": "pytorch_2.0"
# metax   "main_memory-capacity:C550": "pytorch_2.0"
# metax   "computation-FP64:C550": "pytorch_2.0"

# kunlunxin "interconnect-MPI_intraserver:R300p": "pytorch_2.0"
# kunlunxin "interconnect-P2P_intraserver:R300p": "pytorch_2.0"
# kunlunxin "interconnect-MPI_interserver:R300p": "pytorch_2.0"
# kunlunxin "interconnect-P2P_interserver:R300p": "pytorch_2.0"
# kunlunxin "interconnect-h2d:R300p": "pytorch_2.0"
# kunlunxin "main_memory-bandwidth:R300p": "pytorch_2.0"
# kunlunxin "main_memory-capacity:R300p": "pytorch_2.0"
# kunlunxin "computation-FP32:R300p": "pytorch_2.0"
# kunlunxin "computation-FP16:R300p": "pytorch_2.0"
# kunlunxin "computation-BF16:R300p": "pytorch_2.0"
# kunlunxin "computation-INT8:R300p": "pytorch_2.0"
# kunlunxin "computation-TF32:R300p": "pytorch_2.0"

